#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
DATA_DIR="$SCRIPT_DIR/data"
TMP_ENV=""
PROMPT_VALUE=""

cleanup() {
    if [[ -n "${TMP_ENV:-}" && -f "$TMP_ENV" ]]; then
        rm -f -- "$TMP_ENV"
    fi
}
trap cleanup EXIT

die() {
    printf '\n錯誤：%s\n' "$*" >&2
    exit 1
}

ask_yes_no() {
    local prompt="$1"
    local answer

    while true; do
        read -r -p "$prompt [y/N]: " answer || die "輸入已中斷。"
        answer="${answer:-N}"
        case "$answer" in
            y|Y|yes|YES|Yes)
                return 0
                ;;
            n|N|no|NO|No)
                return 1
                ;;
            *)
                printf '請輸入 y 或 n。\n'
                ;;
        esac
    done
}

ask_required() {
    local prompt="$1"
    local secret="${2:-false}"
    local value

    while true; do
        if [[ "$secret" == true ]]; then
            IFS= read -r -s -p "$prompt: " value || die "輸入已中斷。"
            printf '\n'
        else
            read -r -p "$prompt: " value || die "輸入已中斷。"
        fi

        if [[ -n "${value//[[:space:]]/}" ]]; then
            PROMPT_VALUE="$value"
            return 0
        fi

        printf '這個欄位不能留空，請重新輸入。\n'
    done
}

ask_api_id() {
    local value

    while true; do
        read -r -p 'Telegram API ID: ' value || die "輸入已中斷。"
        if [[ "$value" =~ ^[0-9]+$ ]]; then
            PROMPT_VALUE="$value"
            return 0
        fi
        printf 'API ID 必須是純數字，請重新輸入。\n'
    done
}

backup_existing_env() {
    local stamp backup suffix

    if [[ ! -e "$ENV_FILE" ]]; then
        return 0
    fi
    [[ -f "$ENV_FILE" ]] || die "$ENV_FILE 存在，但不是一般檔案。"

    stamp="$(date '+%Y%m%d-%H%M%S')"
    backup="$ENV_FILE.backup.$stamp"
    suffix=1
    while [[ -e "$backup" ]]; do
        backup="$ENV_FILE.backup.$stamp.$suffix"
        suffix=$((suffix + 1))
    done

    cp -p -- "$ENV_FILE" "$backup"
    chmod 600 -- "$backup"
    printf '已備份既有設定：%s\n' "$backup"
}

printf '%s\n' '========================================'
printf '%s\n' ' YTDL Telegram Bot 設定精靈'
printf '%s\n' '========================================'
printf '%s\n' '這個精靈會建立 .env。敏感輸入不會在畫面上回顯。'
printf '%s\n\n' '按 Ctrl+C 可隨時取消；既有 .env 會保持不變。'

printf '%s\n' '第一步：Proxy 設定'
if ask_yes_no '要使用 Cloudflare WARP proxy 嗎？'; then
    USE_WARP=true
else
    USE_WARP=false
fi

if ask_yes_no '要使用 YouTube Cookie 嗎？'; then
    USE_COOKIE=true
else
    USE_COOKIE=false
fi

printf '\n%s\n' '第二步：Telegram 憑證'
printf '%s\n' 'BOT_TOKEN：到 Telegram 的 @BotFather 輸入 /newbot 後取得。'
printf '%s\n' 'API ID / API Hash：登入 https://my.telegram.org/，進入 API development tools 建立 application。'
printf '%s\n\n' 'API ID 與 API Hash 供 Local Telegram Bot API Server 使用。'

ask_required 'Telegram Bot Token' true
BOT_TOKEN="$PROMPT_VALUE"

ask_api_id
TELEGRAM_API_ID="$PROMPT_VALUE"

ask_required 'Telegram API Hash' true
TELEGRAM_API_HASH="$PROMPT_VALUE"

if [[ "$USE_WARP" == true ]]; then
    PROXY_LIST='socks5://warpuser:warppass@warp-proxy:1080'
else
    PROXY_LIST=''
fi

mkdir -p -- "$DATA_DIR"
TMP_ENV="$(mktemp "$SCRIPT_DIR/.env.tmp.XXXXXX")"
chmod 600 -- "$TMP_ENV"

cat > "$TMP_ENV" <<EOF
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')

# Telegram Bot
BOT_TOKEN=$BOT_TOKEN
ALLOWED_CHAT_IDS=

# Telegram Local Bot API Server
API_URL=http://host.docker.internal:8081/bot
TELEGRAM_API_ID=$TELEGRAM_API_ID
TELEGRAM_API_HASH=$TELEGRAM_API_HASH

# Proxies for yt-dlp
PROXY_LIST=$PROXY_LIST

# Cloudflare WARP Proxy
WARP_SOCKS_PORT=1080
WARP_HTTP_PORT=8080
WARP_RESTART_PORT=9090
WARP_USERNAME=warpuser
WARP_PASSWORD=warppass

# Limits
MAX_DISK_GB=10
SUBSCRIPTION_CHECK_INTERVAL=300

# Live recording proxy recovery
LIVE_PROXY_RECOVERY_WINDOW_SECONDS=1800
LIVE_PROXY_RETRY_INITIAL_SECONDS=3
LIVE_PROXY_RETRY_MAX_SECONDS=60
LIVE_WARP_RESTART_COOLDOWN_SECONDS=60
LIVE_END_CONFIRMATIONS=2
LIVE_END_CONFIRMATION_INTERVAL_SECONDS=15

# yt-dlp upgrades
YTDLP_AUTO_UPDATE=true
YTDLP_DAILY_UPDATE=true
YTDLP_UPDATE_TIME=04:00
YTDLP_UPDATE_TIMEZONE=Asia/Taipei
EOF

backup_existing_env
mv -- "$TMP_ENV" "$ENV_FILE"
TMP_ENV=""
chmod 600 -- "$ENV_FILE"

printf '\n設定完成：%s\n' "$ENV_FILE"
printf '%s\n' '已將 .env 權限設為 600。'

if [[ "$USE_COOKIE" == true ]]; then
    printf '\n%s\n' 'Cookie 設定提醒：'
    if [[ -s "$DATA_DIR/cookies.txt" ]]; then
        printf '%s\n' '已偵測到 data/cookies.txt，Bot 會自動使用它。'
    else
        printf '%s\n' '請從瀏覽器匯出 yt-dlp 支援的 Netscape 格式 cookies.txt，然後執行：'
        printf '  cp /你的/cookies.txt %s/cookies.txt\n' "$DATA_DIR"
        printf '  chmod 600 %s/cookies.txt\n' "$DATA_DIR"
    fi
else
    if [[ -s "$DATA_DIR/cookies.txt" ]]; then
        printf '\n%s\n' '提醒：data/cookies.txt 已存在；Bot 仍會自動使用這份 Cookie。'
    fi
fi

printf '\n%s\n' '下一步：'
printf '%s\n' '  docker-compose up -d --build --force-recreate'
printf '%s\n' '  docker-compose logs -f ytdl-bot'
